### ISSUE TITLE
Resource for julia multiprocessing

### ISSUE THREAD

**Issue by jpfairbanks** [timholy/ComputationalResources.jl#8]
Is there any reason not to use this package for managing distributed computing with Julia processes?

**Comment by timholy** [comment]
I'm not aware of any. As you probably already noticed, it's basically a tiny "intent-signaling" package. I'd be happy to consider extensions if you discover you need them.

**Comment by jpfairbanks** [comment]
Ok yeah I think this is a way for us to handle parallelism for LightGraphs. Where the algorithms and datastructures need to change based on the resources you want to use. I think we would want something like CPUThreads but for for processes. `CPUProcesses`? Or use case would probably have in the Settings field

* Number of Threads
* PartitionScheme `Replicated, OneDPartition, TwoDPartition`

Where 1D partition is for splitting vertices and 2D partition is for spliting edges. Like in MPI for linear algebra.

**Comment by timholy** [comment]
Sounds great to me. Since the only "generic" parameter here might be `nthreads` and you're the first/only consumer of this functionality, I'd say just write your own specialized object for that `settings` field and you're good to go. If we find ourselves getting a huge number of clients of that functionality we could think about abstractions when we have enough examples to think about.

**Comment by timholy** [comment]
Closed by #9
